import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Button, FormControl, FormControlLabel, FormLabel, Radio, RadioGroup } from '@mui/material'
import React, { useState } from 'react';
import { Option } from '@/components/Option';
import { OptionProps } from '@/interfaces';
import { options } from '@/data';

export default function Home() {

  const [value, setValue] = useState('piedra');

  const handleSubmit = (value: string) => {
    console.log(value)
  }

  return (
    <>
      <Head>
        <title>Piedra Papel o Tijera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.flex}>
          <FormControl>
            <FormLabel id="demo-row-radio-buttons-group-label">Piedra Papel o Tijera</FormLabel>
            <RadioGroup
              defaultValue={options[0].value}
              onChange={(event) => { setValue(event?.target.value) }}
              row
              aria-labelledby="demo-row-radio-buttons-group-label"
              name="row-radio-buttons-group"
            >
              {
                options.map((option: OptionProps) => {
                  return (
                    <>
                      <Option key={option.name} {...option} />
                    </>
                  );
                })
              }
            </RadioGroup>
            <Button onClick={() => handleSubmit(value)} variant="outlined">Jugar</Button>
          </FormControl>
        </div>
      </main>
    </>
  )
}
