import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Button, FormControl, FormLabel, RadioGroup } from '@mui/material'
import React, { useState } from 'react';
import { Option } from '@/components/Option';
import { OptionProps, validValue } from '@/interfaces';
import { options } from '@/data';

export default function Home() {

  const [value, setValue] = useState('piedra');

  const handleSubmit = (value: validValue) => {
    const valueCPU = options[Math.floor(Math.random() * 3)].value // options[1].value
    console.log({ value, valueCPU })

    if (value == valueCPU) {
      alert('Empate de pana 🤝🏻')
      return;
    }

    switch (value) {

      case 'piedra':
        if (valueCPU == 'tijera') {
          alert(`User Gana 🤝🏻 ${valueCPU}`)
        } else {
          alert(`CPU gana ${valueCPU}`)
        }
        break;

      case 'papel':
        if (valueCPU == 'piedra') {
          alert(`User Gana 🤝🏻 ${valueCPU}`)
        } else {
          alert(`CPU gana ${valueCPU}`)
        }
        break;

      case 'tijera':
        if (valueCPU == 'papel') {
          alert(`User Gana 🤝🏻 ${valueCPU}`)
        } else {
          alert(`CPU gana ${valueCPU}`)
        }
        break;

      default:
        break;
    }
  }

  return (
    <>
      <Head>
        <title>Piedra Papel o Tijera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.flex}>
          <FormControl>
            <FormLabel id="demo-row-radio-buttons-group-label">Piedra Papel o Tijera</FormLabel>
            <RadioGroup
              defaultValue={options[0].value}
              onChange={(event) => { setValue(event?.target.value) }}
              row
              aria-labelledby="demo-row-radio-buttons-group-label"
              name="row-radio-buttons-group"
            >
              {
                options.map((option: OptionProps) => {
                  return (
                    <>
                      <Option key={option.name} {...option} />
                    </>
                  );
                })
              }
            </RadioGroup>
            <Button onClick={() => handleSubmit(value)} variant="outlined">Jugar</Button>
          </FormControl>
        </div>
      </main>
    </>
  )
}
